#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo '[Husky] 🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo '[Husky] please be patient, this may take a while...'

# Check ESLint Standards
yarn format && yarn lint

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
